### ISSUE TITLE
Fixed problem with AntiLag on autoload

### ISSUE THREAD

**Issue by Adiru3** [AdiruNetwork/LatencyOptimizer#1]
`reg.exe delete HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run /f /v ANTI_LAG_APP`
**reinstall AntiLag**

Or download here:
[Fixed problem with AntiLag on autoload.zip](https://github.com/AdiruNetwork/LatencyOptimizer/files/11681209/Fixed.problem.with.AntiLag.on.autoload.zip)

**Comment by RAYK1S** [comment]
It's a shame that such a good project but no reviews.

**Comment by Adiru3** [comment]
> Жаль, что такой хороший проект, но нет отзывов.

Thank you! Actually, this project is no longer active. I consider it outdated, so I have shifted my focus to Amaze projects. If you are interested, please take a look at them!
